### YamlMime:Yaml
ms.openlocfilehash: 284722497853518aaa1b76bde5eecc41f6922b1b
ms.sourcegitcommit: edf2a9241075d5e489f0426412e828c53c8e25e7
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 01/27/2021
ms.locfileid: "50031098"
php:
  preset: laravel
  disabled:
  - no_unused_imports
  finder:
    not-name:
    - index.php
    - server.php
js:
  finder:
    not-name:
    - webpack.mix.js
css: true
